### ISSUE TITLE
[FEATURE] ARM64v8 support.

### ISSUE THREAD

**Issue by Xeddius** [nurdism/neko#103]
I would like to host this on my Raspberry PI4 4gb board.
It'll need to be arm64 since armhf performs extremely poorly on the PI4.
I would set it up manually by myself if I had the time.

The PI4 performs extremely well with arm64 (aarch64) and should be able to work within the requirements.

**Comment by GigaFyde** [comment]
This shouldn't be impossible I think.

**Comment by nurdism** [comment]
should be doable but I dont have a PI4 to mess with so I wont be able to do this myself

**Comment by Xeddius** [comment]
I have one that I can provide remote access to in the next few days.

**Comment by GigaFyde** [comment]
Hey there @Xeddius 

I recently got myself a rpi4 4gb, and with the help of @m1k1o managed to package an ARM64 docker image of neko.
Whilst it technically works, performance is still awful.
There was only a very small performance increase going from ARMv7 to ARM64v8

Feel free to give it a test yourself, but don't get your hopes up too much.
`gigafyde/neko:firefox-arm64`

**Comment by mbattista** [comment]
Hi @GigaFyde and @Xeddius 

I also made a working ARMv7 container.
Since I use HW acceleration parameter in the pipeline it runs smooth on my rpi3 for normal websites.
YouTube kind of works/plays, but its not that smooth. But I think the rpi3 is here the limiting factor?
Perhaps one of you can give me feedback if it runs better on a rpi4.

Important the video played only on a windows system. I could not get any video on linux. (perhaps a missing codec, but I thought chrome has all important codecs preinstalled)

docker-compose.yml:
```
version: "3.4"
services:
  neko:
    image: "mbattista/neko:arm_firefox"
    restart: "unless-stopped"
    # increase on rpi's with more then 1gb ram
    shm_size: "740mb"
    ports:
      - "8084:8080"
      - "52000-52100:52000-52100/udp"
        #    volumes:
        #      - "./certs:/certs"
    # this is important since we need a GPU for hardware acceleration alternatively mount the devices into the docker
    privileged: true
    environment:
      NEKO_SCREEN: '1280x720@30'
      NEKO_PASSWORD: 'neko'
      NEKO_PASSWORD_ADMIN: 'admin'
      NEKO_EPR: 52000-52100
      NEKO_VP8: 'false'
      NEKO_VP9: 'false'
      NEKO_H264: 'true'
      # Change target bitrate and framerate on this parameter
      NEKO_VIDEO: ' ximagesrc display-name=%s use-damage=0 show-pointer=true use-damage=false ! video/x-raw,framerate=30/1 ! videoconvert ! queue ! omxh264enc target-bitrate=1500000 control-rate=4 ! h264parse config-interval=3  ! video/x-h264,profile=baseline,stream-format=byte-stream '
      NEKO_MAX_FPS: 0
      NEKO_OPUS: 'true'
      #      NEKO_CERT: '/certs/cert.pem'
      #      NEKO_KEY: '/certs/key.pem'
```

@m1k1o should I make another pull request for the arm containers? They need to be cross-build in the pipeline
