### ISSUE TITLE
How to use neko behind a reverse proxy?

### ISSUE THREAD

**Issue by sebastianwachter** [nurdism/neko#18]
Hello I am using traefik as a reverse proxy. I start the container on my server using this configuration:

```yml
[...]
  environment:
    - NEKO_WIDTH=1280
    - NEKO_HEIGHT=720
    - NEKO_PASSWORD=password
  labels:
    - "traefik.enable=true"
    - "traefik.http.routers.neko.rule=Host(`neko.domain.tld`)"
    - "traefik.http.routers.neko.tls.certresolver=staging"
    - "traefik.http.routers.neko.entrypoints=websecure"
    - "traefik.http.services.neko.loadbalancer.server.port=8080"
    - "traefik.docker.network=proxy"
[...]
```

As I try to log in using the password I get an error tellting me "unable to connect to server". Inspecting the network traffic in the developer tools I saw the `/ws`  route and also added it to the label configuration:

```yml
    - "traefik.http.routers.neko-websocket.rule=Host(`neko.domain.tld`) && Path(`/ws`)"
```

But it still does not let me log in to neko (gives the same error).

I think there are still ports missing in the configuration of my neko compose file.
