### ISSUE TITLE
Allow firefox addons installation

### ISSUE THREAD

**Issue by sergix44** [nurdism/neko#21]
Hi,
It's possible to add a config to allow the installation of the firefox addons? It can be useful for using youtube enhancer plugins, change adblocker or remove it, etc.

**Comment by nurdism** [comment]
My only concern with this is it could open up the container for security exploits. Anyone else have any input on this. I wanted to make the browser somewhat locked down because it is public.

**Comment by sad** [comment]
Inside `docker-compose.yml`, you can use 'volumes' to mount your own configuration files for Firefox (or anything else) without having to rebuild the container yourself. In my opinion, this is the easiest fix for your problem. You can use the [Enterprise Policy Generator](https://addons.mozilla.org/en-GB/firefox/addon/enterprise-policy-generator/) addon for Firefox to generate a `policies.json`, and then mount it inside the container. My `docker-compose.yml` looks like this:

```
version: '2.0'
services:
  neko:
    container_name: neko
    env_file: .env
    image: nurdism/neko
    restart: always
    shm_size: '2gb'
    ports:
      - "4242:8080"
    environment:
      NEKO_URL: 'https://google.co.uk'
      NEKO_DISPLAY: 0
      NEKO_WIDTH: 1280
      NEKO_HEIGHT: 720
      NEKO_PASSWORD: $PASS
      NEKO_BIND: :8080
      NEKO_ADMIN: $ADMIN
    volumes:
      - "./configs/firefox/policies.json:/usr/share/firefox-esr/distribution/policies.json"
      - "./configs/firefox/autoconfig.js:/usr/lib/firefox-esr/defaults/pref/autoconfig.js"
      - "./configs/firefox/config.js:/usr/lib/firefox-esr/mozilla.cfg"
```

I created a folder called `configs/firefox` in the same location as my compose file, and placed my own configurations in there. You could always just edit any of the [configuration files neko ships with](https://github.com/nurdism/neko/tree/master/.docker/files/firefox). You can do the same for any other files (including openbox config, etc). 

If you change the configuration this way, it allows neko to ship with sensible defaults for Firefox, but still allows customisability for the end user.
