### ISSUE TITLE
[BUG] Chromium not working

### ISSUE THREAD

**Issue by LoicBersier** [nurdism/neko#76]
**Describe the bug**
Chromium crash on startup

**To Reproduce**
use nurdism/neko:chromium for the container

**Expected behavior**
Chromium should launch

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Brave
 - Version 1.7.92

**Additional context**
```
version: "2.0"
services:
  neko:
    image: nurdism/neko:chromium
    restart: always
    shm_size: "1gb"
    ports:
      - "9999:8080"
      - "59000-59100:59000-59100/udp"
    environment:
      DISPLAY: :99.0
      NEKO_PASSWORD: neko
      NEKO_PASSWORD_ADMIN: admin
      NEKO_BIND: :8080
      NEKO_EPR: 59000-59100
```
Server is running Fedora 31

**Client Log:**
```
No issue on client
```

**Server Log:**
```
https://pastebin.com/raw/vVszw0Wg
```
