### ISSUE TITLE
[FEATURE] Add option to enable stereo audio playback

### ISSUE THREAD

**Issue by alectrocute** [nurdism/neko#96]
**Is your feature request related to a problem? Please describe.**
Nope, just an plain ol' feature request.

**Describe the solution you'd like**
I'd love to be able to launch `neko` with 2-channel stereo (instead of 1-2 channel mono) audio piped to peers.

**Comment by m1k1o** [comment]
With opus encoder, try this:

```yml
    environment:
      NEKO_AUDIO: pulsesrc device=%s ! audio/x-raw,channels=2 ! audioconvert ! opusenc
```

**Comment by alectrocute** [comment]
> With opus encoder, try this:
> 
> ```yaml
>     environment:
>       NEKO_AUDIO: pulsesrc device=%s ! audio/x-raw,channels=2 ! audioconvert ! opusenc
> ```

@m1k1o Wonderful, I'm going to give this a go. Thanks!

**Comment by alectrocute** [comment]
@m1k1o Do I enable opus encoder like so?

```yaml
environment:
    NEKO_OPUS: null
    NEKO_AUDIO: pulsesrc device=%s ! audio/x-raw,channels=2 ! audioconvert ! opusenc
```
